### ISSUE TITLE
Researching 5D's sitemaps

### ISSUE THREAD

**Issue by khaipham2204** [khaipham2204/5D-Web-CMS#1]

**Comment by thaihungdoan2** [comment]
[sitemap_5D.pptx](https://github.com/khaipham2204/5D-Web-CMS/files/4750444/sitemap_5D.pptx)

**Comment by khaipham2204** [comment]
Home
|_____ Product
|_____ Service
|_____ About
|_____ Contact

**Comment by khaipham2204** [comment]
> [sitemap_5D.pptx](https://github.com/khaipham2204/5D-Web-CMS/files/4750444/sitemap_5D.pptx)

**Comment by khaipham2204** [comment]
Service:
+ Nông nghiệp

**Comment by khaipham2204** [comment]
Product:
- Nhà màng  
- Homefarm
- Nhà nấm
- Microwave
- Hyperspectral
- ....

**Comment by khaipham2204** [comment]
About -> Tham khảo trang khác.

**Comment by khaipham2204** [comment]
Contact -> thông tin liên hệ.
