### ISSUE TITLE
Research other pages

### ISSUE THREAD

**Issue by khaipham2204** [khaipham2204/5D-Web-CMS#8]

**Comment by khaipham2204** [comment]
https://www.pinterest.com/pin/452471093810814205/?autologin=true&nic_v1=1a7eusBOK9A3Vq1EpHXFZ0ncj9kAlB1iB7VKCmn2bfzl6Cw9jop3pSETiNfFvAvEX2

**Comment by NguyenLinh1996** [comment]
https://themeforest.net/item/pro-garden-gardening-lawn-landscaping-html-template/21326807?ref=Datasata
